import { ParameterConfig } from './types';

export const PARAMETERS: ParameterConfig[] = [
  {
    key: 'ventasMensuales',
    label: 'Ventas mensuales (todos los PdV)',
    default: 400_000_000,
    min: 50_000_000,
    max: 2_000_000_000,
    step: 10_000_000,
    format: 'currency',
    sublabel: 'Ingresos totales de todos los puntos de venta',
    group: 'financiero',
  },
  {
    key: 'costoAlimentosPct',
    label: 'Costo de alimentos (% sobre venta)',
    default: 0.44,
    min: 0.25,
    max: 0.55,
    step: 0.01,
    format: 'percentage',
    sublabel: 'Promedio Colombia 2025-2026: 44% (Acodres)',
    group: 'financiero',
  },
  {
    key: 'ticketPromedio',
    label: 'Ticket promedio por plato',
    default: 35_000,
    min: 10_000,
    max: 120_000,
    step: 1_000,
    format: 'currency',
    group: 'financiero',
  },
  {
    key: 'varianzaAvtActual',
    label: 'Varianza AvT actual estimada',
    default: 0.10,
    min: 0.02,
    max: 0.25,
    step: 0.005,
    format: 'percentage',
    sublabel: 'Sin sistema de control: típicamente 5-15%',
    group: 'operativo',
  },
  {
    key: 'mermaTransito',
    label: 'Merma en tránsito estimada',
    default: 0.03,
    min: 0,
    max: 0.10,
    step: 0.005,
    format: 'percentage',
    sublabel: 'Pérdida entre CDP y PdV (faltantes, robo)',
    group: 'operativo',
  },
  {
    key: 'disponibilidadCarta',
    label: 'Disponibilidad de carta actual',
    default: 0.85,
    min: 0.60,
    max: 0.98,
    step: 0.01,
    format: 'percentage',
    sublabel: '% de platos disponibles para venta',
    group: 'operativo',
  },
  {
    key: 'horasManualDia',
    label: 'Horas manuales / día',
    default: 4,
    min: 0.5,
    max: 12,
    step: 0.5,
    format: 'hours',
    sublabel: 'Conteos + reconteos + digitación + reconciliación',
    group: 'operativo',
  },
  {
    key: 'costoHoraHombre',
    label: 'Costo hora-hombre operario',
    default: 12_000,
    min: 8_000,
    max: 25_000,
    step: 1_000,
    format: 'currency',
    sublabel: 'SMLV 2026 + prestaciones',
    group: 'financiero',
  },
  {
    key: 'sobrecompraPct',
    label: 'Sobrecompra estimada',
    default: 0.02,
    min: 0,
    max: 0.08,
    step: 0.005,
    format: 'percentage',
    sublabel: 'Compras que exceden la demanda real',
    group: 'operativo',
  },
  {
    key: 'sustitucionPct',
    label: 'Tasa de sustitución',
    default: 0.50,
    min: 0.20,
    max: 0.80,
    step: 0.05,
    format: 'percentage',
    sublabel: '% de clientes que piden otro plato si no hay el que quieren',
    group: 'financiero',
  },
  {
    key: 'suscripcionMensual',
    label: 'Suscripción mensual software',
    default: 4_000_000,
    min: 2_000_000,
    max: 10_000_000,
    step: 500_000,
    format: 'currency',
    sublabel: 'Plataforma VitaTag completa',
    group: 'financiero',
  },
];
