import { Solution } from './types';

export const SOLUTIONS: Solution[] = [
  {
    id: 's1',
    name: 'Entrega Certificada Digital',
    shortName: 'Entrega Digital',
    icon: '📦',
    type: 'HW+SW',
    color: '#2980B9',
    description: 'Digitalizar despachos con códigos de barras/QR. Eliminar papel, detectar faltantes al instante.',
    hwCost: 5_793_500,
    swCost: 0,
    consumableMonthly: 50_000,
    impacts: {
      avtReduction: 0.85,
      transitReduction: 0.50,
      dispImprovement: 0.03,
      horasReduction: 0.70,
      sobrecompraReduction: 1.0,
    },
  },
  {
    id: 's2',
    name: 'Recetas como Unidad de Control',
    shortName: 'Recetas',
    icon: '📋',
    type: '100% SW',
    color: '#148F77',
    description: 'Cargar recetas, conectar con POS, calcular consumo teórico vs. real. Detectar mermas ocultas.',
    hwCost: 0,
    swCost: 5_000_000,
    consumableMonthly: 0,
    impacts: {
      avtReduction: 0.65,
      transitReduction: 1.0,
      dispImprovement: 0.04,
      horasReduction: 1.0,
      sobrecompraReduction: 0.40,
    },
  },
  {
    id: 's3',
    name: 'Inteligencia Agéntica',
    shortName: 'IA Agéntica',
    icon: '🤖',
    type: '100% SW',
    color: '#1E8449',
    description: 'IA que detecta patrones, calcula ventas perdidas, alerta anomalías y recomienda acciones 24/7.',
    hwCost: 0,
    swCost: 5_000_000,
    consumableMonthly: 0,
    impacts: {
      avtReduction: 0.70,
      transitReduction: 1.0,
      dispImprovement: 0.03,
      horasReduction: 0.60,
      sobrecompraReduction: 0.50,
    },
  },
  {
    id: 's4',
    name: 'Trazabilidad Física Avanzada',
    shortName: 'Trazabilidad',
    icon: '🔒',
    type: 'HW+SW',
    color: '#303C42',
    description: 'Tags RFID en canastas o QR en cajas. Trazabilidad completa del transporte CDP→PdV.',
    hwCost: 3_000_000,
    swCost: 2_000_000,
    consumableMonthly: 30_000,
    impacts: {
      avtReduction: 0.90,
      transitReduction: 0.33,
      dispImprovement: 0.01,
      horasReduction: 1.0,
      sobrecompraReduction: 1.0,
    },
  },
];
